/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type { IPostgresInterval } from "postgres-interval";

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthAuthorizationStatus = "approved" | "denied" | "expired" | "pending";

export type AuthOauthClientType = "confidential" | "public";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOauthResponseType = "code";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type EpisodicMemoryErrorClass = "CONTEXT_HYDRATION_FAILURE" | "LLM_HALLUCINATION" | "LLM_PARSE_ERROR" | "PERMISSION_DENIED" | "RESOURCE_EXHAUSTED" | "TIMEOUT_EXCEEDED" | "TOOL_EXECUTION_FAILURE" | "TOOL_SCHEMA_MISMATCH" | "TRANSITION_INVALID" | "UNKNOWN";

export type EpisodicMemoryEventCategory = "AGENT_ACTION" | "DATA_CHANGE" | "INTEGRATION" | "PERFORMANCE" | "SECURITY" | "SYSTEM" | "USER_ACTION";

export type EpisodicMemoryEventSeverity = "CRITICAL" | "DEBUG" | "ERROR" | "INFO" | "NOTICE" | "WARNING";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Interval = ColumnType<IPostgresInterval, IPostgresInterval | number | string, IPostgresInterval | number | string>;

export type ItemType = "document" | "folder";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadStatus = "contacted" | "lost" | "negotiation" | "new" | "proposal" | "qualified" | "won";

export type Numeric = ColumnType<string, number | string, number | string>;

export type ProceduralMemoryExecutionStatus = "cancelled" | "completed" | "failed" | "pending" | "running" | "timeout";

export type ProceduralMemoryProtocolStatus = "active" | "archived" | "deprecated" | "draft" | "testing";

export type SemanticMemoryEntityStatus = "active" | "archived" | "draft" | "flagged" | "merged";

export type SemanticMemoryRelationshipType = "created_by" | "depends_on" | "derived_from" | "is_a" | "located_in" | "opposite_of" | "part_of" | "related_to" | "same_as" | "works_for";

export type StorageBuckettype = "ANALYTICS" | "STANDARD" | "VECTOR";

export type SystemRole = "super_admin" | "user";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WorkspaceRole = "admin" | "member" | "owner" | "viewer";

export interface AgentRuntimeProtocolExecutions {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp | null>;
  current_step: string | null;
  error_message: string | null;
  id: Generated<string>;
  llm_calls: Generated<number | null>;
  protocol_id: string;
  /**
   * Hydrated context data available during execution
   */
  scaffold: Generated<Json | null>;
  started_at: Timestamp | null;
  status: Generated<string>;
  step_outputs: Generated<Json | null>;
  steps_completed: Generated<string[] | null>;
  total_tokens: Generated<number | null>;
  trigger_payload: Json | null;
  trigger_type: string;
  workspace_id: string;
}

export interface AgentRuntimeProtocols {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  /**
   * JSON definition validated against PROTOCOL_SCHEMA - the DNA of agent behavior
   */
  definition: Json;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  is_system: Generated<boolean | null>;
  max_steps: Generated<number | null>;
  name: string;
  protocol_type: string;
  retry_policy: Generated<Json | null>;
  timeout_seconds: Generated<number | null>;
  updated_at: Generated<Timestamp | null>;
  version: Generated<string>;
  workspace_id: string;
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthFlowState {
  auth_code: string;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string;
  code_challenge_method: AuthCodeChallengeMethod;
  created_at: Timestamp | null;
  id: string;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  last_webauthn_challenge_data: Json | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOauthAuthorizations {
  approved_at: Timestamp | null;
  authorization_code: string | null;
  authorization_id: string;
  client_id: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: string;
  nonce: string | null;
  redirect_uri: string;
  resource: string | null;
  response_type: Generated<AuthOauthResponseType>;
  scope: string;
  state: string | null;
  status: Generated<AuthOauthAuthorizationStatus>;
  user_id: string | null;
}

export interface AuthOauthClients {
  client_name: string | null;
  client_secret_hash: string | null;
  client_type: Generated<AuthOauthClientType>;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grant_types: string;
  id: string;
  logo_uri: string | null;
  redirect_uris: string;
  registration_type: AuthOauthRegistrationType;
  updated_at: Generated<Timestamp>;
}

export interface AuthOauthClientStates {
  code_verifier: string | null;
  created_at: Timestamp;
  id: string;
  provider_type: string;
}

export interface AuthOauthConsents {
  client_id: string;
  granted_at: Generated<Timestamp>;
  id: string;
  revoked_at: Timestamp | null;
  scopes: string;
  user_id: string;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  oauth_client_id: string | null;
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refresh_token_counter: Int8 | null;
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refresh_token_hmac_key: string | null;
  refreshed_at: Timestamp | null;
  scopes: string | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface Blocks {
  content: Generated<Json>;
  content_hash: Generated<string | null>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  document_id: string;
  embedding: Generated<string | null>;
  embedding_updated_at: Timestamp | null;
  id: Generated<string>;
  last_edited_by: string | null;
  parent_path: Generated<string>;
  sort_order: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface CrmLeads {
  assigned_to: string | null;
  company: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  email: string;
  id: Generated<string>;
  name: string;
  notes: string | null;
  status: Generated<LeadStatus>;
  updated_at: Generated<Timestamp | null>;
  value: Generated<Numeric>;
  workspace_id: string;
}

export interface CronJob {
  active: Generated<boolean>;
  command: string;
  database: Generated<string>;
  jobid: Generated<Int8>;
  jobname: string | null;
  nodename: Generated<string>;
  nodeport: Generated<number>;
  schedule: string;
  username: Generated<string>;
}

export interface CronJobRunDetails {
  command: string | null;
  database: string | null;
  end_time: Timestamp | null;
  job_pid: number | null;
  jobid: Int8 | null;
  return_message: string | null;
  runid: Generated<Int8>;
  start_time: Timestamp | null;
  status: string | null;
  username: string | null;
}

export interface DashboardStatsLive {
  documents_count: Generated<Int8 | null>;
  folders_count: Generated<Int8 | null>;
  items_last_24h: Generated<Int8 | null>;
  items_last_7d: Generated<Int8 | null>;
  last_updated_at: Generated<Timestamp | null>;
  total_items_count: Generated<Int8 | null>;
  update_version: Generated<Int8 | null>;
  updates_last_24h: Generated<Int8 | null>;
  workspace_id: string;
}

export interface DocumentEmbeddings {
  chunk_index: number;
  content: string;
  created_at: Generated<Timestamp | null>;
  document_id: string;
  /**
   * Vector embedding (1536 dimensions) generated by OpenAI text-embedding-3-small model.
   */
  embedding: string;
  /**
   * Array representing the hierarchical path of headers leading to this chunk (e.g., ["Introduction", "Background", "Problem Statement"]).
   */
  header_path: Generated<string[]>;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  /**
   * Denormalized workspace_id for efficient RLS pre-filtering. CRITICAL for security - ensures vector search respects workspace boundaries.
   */
  workspace_id: string;
}

export interface Documents {
  archived_at: Timestamp | null;
  content: Generated<Json>;
  cover_image_url: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  icon: Generated<string | null>;
  id: Generated<string>;
  is_archived: Generated<boolean | null>;
  is_template: Generated<boolean>;
  last_edited_by: string | null;
  parent_id: string | null;
  path: Generated<string>;
  search_vector: Generated<string | null>;
  title: Generated<string>;
  updated_at: Generated<Timestamp | null>;
  widget_index: Generated<string[] | null>;
  workspace_id: string;
}

export interface EntityEdges {
  /**
   * Timestamp when the relationship was first recorded.
   */
  created_at: Generated<Timestamp | null>;
  /**
   * Unique identifier for the edge.
   */
  id: Generated<string>;
  /**
   * Flexible metadata for edge properties such as confidence weights or labels.
   */
  properties: Generated<Json | null>;
  /**
   * The semantic type of the relationship (e.g., mentions, assigned_to, blocks).
   */
  relation_type: string;
  /**
   * UUID of the origin node (document, lead, user, task, or item).
   */
  source_id: string;
  /**
   * Entity type of the origin node.
   */
  source_type: string;
  /**
   * UUID of the destination node.
   */
  target_id: string;
  /**
   * Entity type of the destination node.
   */
  target_type: string;
  /**
   * Timestamp when the relationship metadata was last changed.
   */
  updated_at: Generated<Timestamp | null>;
  /**
   * The workspace this edge belongs to for multi-tenant isolation.
   */
  workspace_id: string;
}

export interface EpisodicMemoryErrorLogs {
  actual_output: Json | null;
  created_at: Generated<Timestamp>;
  diagnosed_at: Timestamp | null;
  diagnosis: Json | null;
  error_class: EpisodicMemoryErrorClass;
  error_code: string | null;
  error_message: string;
  execution_id: string;
  expected_schema: Json | null;
  fingerprint: string | null;
  id: Generated<string>;
  patch_version: number | null;
  patched_at: Timestamp | null;
  protocol_id: string;
  protocol_version: number;
  stack_trace: string | null;
  step_id: string;
  step_input: Json | null;
  step_output: Json | null;
}

export interface EpisodicMemoryErrorPatterns {
  affected_protocols: string[] | null;
  diagnosed_count: Int8 | null;
  error_class: EpisodicMemoryErrorClass | null;
  error_code: string | null;
  fingerprint: string | null;
  last_occurrence: Timestamp | null;
  occurrence_count: Int8 | null;
  patched_count: Int8 | null;
  step_id: string | null;
}

export interface EpisodicMemoryEvents {
  actor_id: string | null;
  actor_type: string | null;
  category: EpisodicMemoryEventCategory;
  correlation_id: string | null;
  created_at: Generated<Timestamp>;
  details: Generated<Json | null>;
  event_type: string;
  id: Generated<string>;
  session_id: string | null;
  severity: Generated<EpisodicMemoryEventSeverity>;
  source_system: string | null;
  summary: string;
}

export interface EpisodicMemorySessions {
  agent_id: string | null;
  context: Generated<Json | null>;
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  event_count: Generated<number | null>;
  id: Generated<string>;
  last_event_at: Timestamp | null;
  session_type: string;
  status: Generated<string>;
  summary: string | null;
  user_id: string | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface Items {
  created_at: Generated<Timestamp | null>;
  created_by: string;
  document_id: string | null;
  id: Generated<string>;
  item_type: Generated<ItemType>;
  name: string;
  /**
   * Direct parent reference maintained for referential integrity and simpler parent lookups
   */
  parent_id: string | null;
  /**
   * Materialized path using ltree extension. Format: root.segment1.segment2. Enables O(1) ancestor/descendant lookups
   */
  path: string;
  /**
   * Fractional indexing key for O(1) reordering. Uses Base62 lexicographical strings. COLLATE C ensures deterministic sorting.
   */
  rank_key: Generated<string>;
  /**
   * Manual ordering within siblings. Use fractional indexing for drag-and-drop operations
   */
  sort_order: Generated<number | null>;
  updated_at: Generated<Timestamp | null>;
  workspace_id: string;
}

export interface KnowledgeGraphEdges {
  confidence: Generated<Numeric | null>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  relationship: string;
  source_block_id: string | null;
  source_entity: string;
  source_entity_type: string;
  target_entity: string;
  target_entity_type: string;
  updated_at: Generated<Timestamp>;
  valid_from: Generated<Timestamp>;
  valid_to: Timestamp | null;
  workspace_id: string;
}

export interface MigrationEntityResolutionBatches {
  batch_number: number;
  completed_at: Timestamp | null;
  duplicates_found: Generated<number | null>;
  entities_processed: Generated<number | null>;
  error_message: string | null;
  id: Generated<number>;
  merges_performed: Generated<number | null>;
  started_at: Generated<Timestamp | null>;
  status: Generated<string | null>;
}

export interface MigrationEntityResolutionMatches {
  batch_id: number | null;
  duplicate_id: string;
  golden_record_id: string;
  id: Generated<Int8>;
  match_type: string;
  merged_at: Timestamp | null;
  similarity_score: Numeric;
}

export interface MigrationMigrationLog {
  details: Json | null;
  id: Generated<Int8>;
  level: string;
  logged_at: Generated<Timestamp | null>;
  message: string;
  migration_name: string;
}

export interface MigrationMigrationStatus {
  completed_at: Timestamp | null;
  failed_rows: Generated<Int8 | null>;
  id: Generated<number>;
  last_migrated_id: string | null;
  migrated_rows: Generated<Int8 | null>;
  migration_name: string;
  notes: string | null;
  phase: Generated<string>;
  phase_changed_at: Generated<Timestamp | null>;
  started_at: Timestamp | null;
  total_rows: Int8 | null;
  validation_errors: Generated<Json | null>;
  validation_passed: boolean | null;
}

export interface MvDeltaQueue {
  applied_to_version: Int8 | null;
  created_at: Generated<Timestamp>;
  delta_documents: Generated<number | null>;
  delta_folders: Generated<number | null>;
  delta_total: Generated<number | null>;
  id: Generated<string>;
  operation: string;
  processed_at: Timestamp | null;
  view_name: string;
  workspace_id: string;
}

export interface MvRefreshQueue {
  id: Generated<string>;
  processed_at: Timestamp | null;
  requested_at: Generated<Timestamp>;
  trigger_source: string | null;
  view_name: string;
  workspace_id: string;
}

export interface NetHttpRequestQueue {
  body: Buffer | null;
  headers: Json | null;
  id: Generated<Int8>;
  method: string;
  timeout_milliseconds: number;
  url: string;
}

export interface NetHttpResponse {
  content: string | null;
  content_type: string | null;
  created: Generated<Timestamp>;
  error_msg: string | null;
  headers: Json | null;
  id: Int8 | null;
  status_code: number | null;
  timed_out: boolean | null;
}

export interface PartConfig {
  async_partitioning_in_progress: string | null;
  automatic_maintenance: Generated<string>;
  constraint_cols: string[] | null;
  constraint_valid: Generated<boolean>;
  control: string;
  date_trunc_interval: string | null;
  datetime_string: string | null;
  epoch: Generated<string>;
  ignore_default_data: Generated<boolean>;
  infinite_time_partitions: Generated<boolean>;
  inherit_privileges: Generated<boolean | null>;
  jobmon: Generated<boolean>;
  maintenance_last_run: Timestamp | null;
  maintenance_order: number | null;
  optimize_constraint: Generated<number>;
  parent_table: string;
  partition_interval: string;
  partition_type: string;
  premake: Generated<number>;
  retention: string | null;
  retention_keep_index: Generated<boolean>;
  retention_keep_publication: Generated<boolean>;
  retention_keep_table: Generated<boolean>;
  retention_schema: string | null;
  sub_partition_set_full: Generated<boolean>;
  template_table: string | null;
  time_decoder: string | null;
  time_encoder: string | null;
  undo_in_progress: Generated<boolean>;
}

export interface PartConfigSub {
  sub_automatic_maintenance: Generated<string>;
  sub_constraint_cols: string[] | null;
  sub_constraint_valid: Generated<boolean>;
  sub_control: string;
  sub_control_not_null: Generated<boolean | null>;
  sub_date_trunc_interval: string | null;
  sub_default_table: Generated<boolean | null>;
  sub_epoch: Generated<string>;
  sub_ignore_default_data: Generated<boolean>;
  sub_infinite_time_partitions: Generated<boolean>;
  sub_inherit_privileges: Generated<boolean | null>;
  sub_jobmon: Generated<boolean>;
  sub_maintenance_order: number | null;
  sub_optimize_constraint: Generated<number>;
  sub_parent: string;
  sub_partition_interval: string;
  sub_partition_type: string;
  sub_premake: Generated<number>;
  sub_retention: string | null;
  sub_retention_keep_index: Generated<boolean>;
  sub_retention_keep_publication: Generated<boolean>;
  sub_retention_keep_table: Generated<boolean>;
  sub_retention_schema: string | null;
  sub_template_table: string | null;
  sub_time_decoder: string | null;
  sub_time_encoder: string | null;
}

export interface PartitionMgmtPartitionConfig {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  parent_schema: string;
  parent_table: string;
  partition_column: string;
  partition_interval: Interval;
  premake_count: Generated<number>;
  retention_period: Interval | null;
}

export interface PartitionMgmtPartitionLog {
  action: string;
  id: Generated<Int8>;
  logged_at: Generated<Timestamp | null>;
  message: string | null;
  parent_table: string;
  partition_name: string;
  range_end: Timestamp | null;
  range_start: Timestamp | null;
}

export interface ProceduralMemoryProtocolExecutions {
  completed_at: Timestamp | null;
  error_message: string | null;
  error_step_id: string | null;
  id: Generated<string>;
  input_data: Generated<Json | null>;
  output_data: Json | null;
  protocol_id: string;
  retry_count: Generated<number | null>;
  session_id: string | null;
  started_at: Generated<Timestamp>;
  status: Generated<ProceduralMemoryExecutionStatus>;
  step_log: Generated<Json | null>;
  trigger_context: Generated<Json | null>;
  triggered_by: string | null;
}

export interface ProceduralMemoryProtocols {
  avg_execution_time_ms: Numeric | null;
  category: string | null;
  created_at: Generated<Timestamp>;
  definition: Json;
  description: string | null;
  execution_count: Generated<Int8 | null>;
  id: Generated<string>;
  last_executed_at: Timestamp | null;
  metadata: Generated<Json | null>;
  name: string;
  owner_id: string | null;
  rank_key: string | null;
  slug: string;
  status: Generated<ProceduralMemoryProtocolStatus>;
  success_count: Generated<Int8 | null>;
  tags: Generated<string[] | null>;
  updated_at: Generated<Timestamp>;
  version: Generated<string>;
}

export interface ProceduralMemoryProtocolVersions {
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  definition: Json;
  id: Generated<string>;
  patch_reason: string | null;
  patched_from_error_id: string | null;
  protocol_id: string;
  version: number;
}

export interface Profiles {
  avatar_url: string | null;
  created_at: Generated<Timestamp | null>;
  default_workspace_id: string | null;
  email: string;
  full_name: string | null;
  id: string;
  system_role: Generated<SystemRole>;
  updated_at: Generated<Timestamp | null>;
}

export interface RealtimeMessages {
  event: string | null;
  extension: string;
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  claims: Json;
  claims_role: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  subscription_id: string;
}

export interface SemanticMemoryEntities {
  canonical_name: string;
  category: string | null;
  confidence_score: Numeric | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  embedding: string | null;
  embedding_model: string | null;
  embedding_updated_at: Timestamp | null;
  entity_type: string;
  external_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  merged_into_id: string | null;
  metadata: Generated<Json | null>;
  /**
   * Fractional index key for manual ordering within category. Use fi_generate_key_between() to generate.
   */
  rank_key: string | null;
  source_system: string | null;
  status: Generated<SemanticMemoryEntityStatus>;
  updated_at: Generated<Timestamp>;
  workspace_id: string | null;
}

export interface SemanticMemoryEntityAliases {
  alias: string;
  alias_type: string;
  created_at: Generated<Timestamp>;
  entity_id: string;
  id: Generated<string>;
  is_primary: Generated<boolean | null>;
  language_code: Generated<string | null>;
  normalized_alias: Generated<string | null>;
  source: string | null;
}

export interface SemanticMemoryEntityProperties {
  confidence: Numeric | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  id: Generated<string>;
  property_name: string;
  property_value: Json;
  source: string | null;
  valid_from: Generated<Timestamp | null>;
  valid_to: Timestamp | null;
}

export interface SemanticMemoryEntityRelationships {
  confidence: Numeric | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  metadata: Generated<Json | null>;
  relationship_subtype: string | null;
  relationship_type: SemanticMemoryRelationshipType;
  source_entity_id: string;
  source_system: string | null;
  target_entity_id: string;
  traversal_priority: Generated<number | null>;
  valid_from: Generated<Timestamp | null>;
  valid_to: Timestamp | null;
  weight: Generated<Numeric | null>;
}

export interface SemanticMemoryGraphExpansionStats {
  avg_relationships_per_entity: Numeric | null;
  connected_entities: Int8 | null;
  total_entities: Int8 | null;
  total_relationships: Int8 | null;
  workspace_id: string | null;
}

export interface SemanticMemoryResolutionConfig {
  auto_match_threshold: Generated<Numeric>;
  blocking_enabled: Generated<boolean>;
  candidate_threshold: Generated<Numeric>;
  check_aliases: Generated<boolean>;
  id: Generated<number>;
  max_candidates_to_check: Generated<number>;
  strict_mode: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null;
  avif_autodetection: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  file_size_limit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageBucketsAnalytics {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  format: Generated<string>;
  id: Generated<string>;
  name: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageBucketsVectors {
  created_at: Generated<Timestamp>;
  id: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucket_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  last_accessed_at: Generated<Timestamp | null>;
  level: number | null;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  path_tokens: Generated<string[] | null>;
  updated_at: Generated<Timestamp | null>;
  user_metadata: Json | null;
  version: string | null;
}

export interface StoragePrefixes {
  bucket_id: string;
  created_at: Generated<Timestamp | null>;
  level: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageS3MultipartUploads {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  in_progress_size: Generated<Int8>;
  key: string;
  owner_id: string | null;
  upload_signature: string;
  user_metadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  owner_id: string | null;
  part_number: number;
  size: Generated<Int8>;
  upload_id: string;
  version: string;
}

export interface StorageVectorIndexes {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  data_type: string;
  dimension: number;
  distance_metric: string;
  id: Generated<string>;
  metadata_configuration: Json | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SuperAdminAuditLog {
  action: string;
  admin_user_id: string | null;
  created_at: Generated<Timestamp | null>;
  details: Json | null;
  id: Generated<string>;
  ip_address: string | null;
  target_id: string | null;
  target_table: string | null;
}

export interface SuperAdminWhitelist {
  created_at: Generated<Timestamp | null>;
  email: string;
  notes: string | null;
}

export interface TablePrivs {
  grantee: string | null;
  grantor: string | null;
  privilege_type: string | null;
  table_name: string | null;
  table_schema: string | null;
}

export interface TestTestResults {
  execution_time_ms: number | null;
  id: Generated<number>;
  message: string | null;
  passed: boolean;
  run_at: Generated<Timestamp | null>;
  test_name: string;
  test_suite: string;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface WorkspaceMembers {
  id: Generated<string>;
  joined_at: Generated<Timestamp | null>;
  role: Generated<WorkspaceRole>;
  user_id: string;
  workspace_id: string;
}

export interface Workspaces {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  name: string;
  owner_id: string;
  settings: Generated<Json | null>;
  slug: string;
  updated_at: Generated<Timestamp | null>;
}

export interface DB {
  "agent_runtime.protocol_executions": AgentRuntimeProtocolExecutions;
  "agent_runtime.protocols": AgentRuntimeProtocols;
  "auth.audit_log_entries": AuthAuditLogEntries;
  "auth.flow_state": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfa_amr_claims": AuthMfaAmrClaims;
  "auth.mfa_challenges": AuthMfaChallenges;
  "auth.mfa_factors": AuthMfaFactors;
  "auth.oauth_authorizations": AuthOauthAuthorizations;
  "auth.oauth_client_states": AuthOauthClientStates;
  "auth.oauth_clients": AuthOauthClients;
  "auth.oauth_consents": AuthOauthConsents;
  "auth.one_time_tokens": AuthOneTimeTokens;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.saml_providers": AuthSamlProviders;
  "auth.saml_relay_states": AuthSamlRelayStates;
  "auth.schema_migrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.sso_domains": AuthSsoDomains;
  "auth.sso_providers": AuthSsoProviders;
  "auth.users": AuthUsers;
  blocks: Blocks;
  crm_leads: CrmLeads;
  "cron.job": CronJob;
  "cron.job_run_details": CronJobRunDetails;
  dashboard_stats_live: DashboardStatsLive;
  document_embeddings: DocumentEmbeddings;
  documents: Documents;
  entity_edges: EntityEdges;
  "episodic_memory.error_logs": EpisodicMemoryErrorLogs;
  "episodic_memory.error_patterns": EpisodicMemoryErrorPatterns;
  "episodic_memory.events": EpisodicMemoryEvents;
  "episodic_memory.sessions": EpisodicMemorySessions;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  items: Items;
  knowledge_graph_edges: KnowledgeGraphEdges;
  "migration.entity_resolution_batches": MigrationEntityResolutionBatches;
  "migration.entity_resolution_matches": MigrationEntityResolutionMatches;
  "migration.migration_log": MigrationMigrationLog;
  "migration.migration_status": MigrationMigrationStatus;
  mv_delta_queue: MvDeltaQueue;
  mv_refresh_queue: MvRefreshQueue;
  "net._http_response": NetHttpResponse;
  "net.http_request_queue": NetHttpRequestQueue;
  part_config: PartConfig;
  part_config_sub: PartConfigSub;
  "partition_mgmt.partition_config": PartitionMgmtPartitionConfig;
  "partition_mgmt.partition_log": PartitionMgmtPartitionLog;
  "procedural_memory.protocol_executions": ProceduralMemoryProtocolExecutions;
  "procedural_memory.protocol_versions": ProceduralMemoryProtocolVersions;
  "procedural_memory.protocols": ProceduralMemoryProtocols;
  profiles: Profiles;
  "realtime.messages": RealtimeMessages;
  "realtime.schema_migrations": RealtimeSchemaMigrations;
  "realtime.subscription": RealtimeSubscription;
  "semantic_memory.entities": SemanticMemoryEntities;
  "semantic_memory.entity_aliases": SemanticMemoryEntityAliases;
  "semantic_memory.entity_properties": SemanticMemoryEntityProperties;
  "semantic_memory.entity_relationships": SemanticMemoryEntityRelationships;
  "semantic_memory.graph_expansion_stats": SemanticMemoryGraphExpansionStats;
  "semantic_memory.resolution_config": SemanticMemoryResolutionConfig;
  "storage.buckets": StorageBuckets;
  "storage.buckets_analytics": StorageBucketsAnalytics;
  "storage.buckets_vectors": StorageBucketsVectors;
  "storage.migrations": StorageMigrations;
  "storage.objects": StorageObjects;
  "storage.prefixes": StoragePrefixes;
  "storage.s3_multipart_uploads": StorageS3MultipartUploads;
  "storage.s3_multipart_uploads_parts": StorageS3MultipartUploadsParts;
  "storage.vector_indexes": StorageVectorIndexes;
  super_admin_audit_log: SuperAdminAuditLog;
  super_admin_whitelist: SuperAdminWhitelist;
  table_privs: TablePrivs;
  "test.test_results": TestTestResults;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
  workspace_members: WorkspaceMembers;
  workspaces: Workspaces;
}
