import type { ColumnType } from 'kysely';

// Custom type for ltree (PostgreSQL extension)
export type Ltree = string;

// Custom type for vector (pgvector extension)
export type Vector = number[];

// Timestamp with timezone
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

// UUID type
export type UUID = string;

// JSONB type
export type JsonB<T = unknown> = ColumnType<T, T | string, T | string>;

// ============================================================================
// Generated Types (kysely-codegen will regenerate these)
// ============================================================================

export interface WorkspacesTable {
  id: ColumnType<UUID, UUID | undefined, never>;
  name: string;
  slug: string;
  owner_id: UUID;
  settings: JsonB<Record<string, unknown>>;
  created_at: ColumnType<Timestamp, Timestamp | undefined, never>;
  updated_at: ColumnType<Timestamp, Timestamp | undefined, Timestamp>;
}

export interface WorkspaceMembersTable {
  id: ColumnType<UUID, UUID | undefined, never>;
  workspace_id: UUID;
  user_id: UUID;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  joined_at: ColumnType<Timestamp, Timestamp | undefined, never>;
}

export interface DocumentsTable {
  id: ColumnType<UUID, UUID | undefined, never>;
  workspace_id: UUID;
  parent_id: UUID | null;
  title: string;
  icon: string | null;
  cover_image_url: string | null;
  is_template: boolean;
  is_archived: boolean;
  archived_at: Timestamp | null;
  created_by: UUID;
  last_edited_by: UUID | null;
  created_at: ColumnType<Timestamp, Timestamp | undefined, never>;
  updated_at: ColumnType<Timestamp, Timestamp | undefined, Timestamp>;
  path: Ltree;
}

export interface BlocksTable {
  id: UUID; // UUIDv7 generated by application
  document_id: UUID;
  parent_path: Ltree;
  type: string;
  content: JsonB<TipTapContent>;
  sort_order: string; // Fractional index
  embedding: Vector | null;
  content_hash: string | null;
  embedding_updated_at: Timestamp | null;
  created_by: UUID | null;
  last_edited_by: UUID | null;
  created_at: ColumnType<Timestamp, Timestamp | undefined, never>;
  updated_at: ColumnType<Timestamp, Timestamp | undefined, Timestamp>;
}

export interface KnowledgeGraphEdgesTable {
  id: ColumnType<UUID, UUID | undefined, never>;
  workspace_id: UUID;
  source_entity: string;
  source_entity_type: string;
  relationship: string;
  target_entity: string;
  target_entity_type: string;
  source_block_id: UUID | null;
  valid_from: ColumnType<Timestamp, Timestamp | undefined, never>;
  valid_to: Timestamp | null;
  confidence: number;
  metadata: JsonB<Record<string, unknown>>;
  created_at: ColumnType<Timestamp, Timestamp | undefined, never>;
  updated_at: ColumnType<Timestamp, Timestamp | undefined, Timestamp>;
}

// TipTap content structure
export interface TipTapContent {
  type?: string;
  text?: string;
  marks?: Array<{ type: string; attrs?: Record<string, unknown> }>;
  attrs?: Record<string, unknown>;
  content?: TipTapContent[];
}

// Main database interface
export interface DB {
  workspaces: WorkspacesTable;
  workspace_members: WorkspaceMembersTable;
  documents: DocumentsTable;
  blocks: BlocksTable;
  knowledge_graph_edges: KnowledgeGraphEdgesTable;
}

// Helper for row types
import type { Selectable } from 'kysely';
export type Tables<T extends keyof DB> = Selectable<DB[T]>;