// This file will be auto-generated by Supabase CLI
// Placeholder until schema is deployed
export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {}
        Views: {}
        Functions: {}
        Enums: {}
    }
}
