-- ============================================
-- COMMAND CENTER ERP V2.0 - VECTOR STORE INFRASTRUCTURE
-- ============================================
-- Phase 2: Semantic Search & RAG Pipeline
-- This migration creates the document_embeddings table
-- with pgvector extension for semantic search capabilities
-- ============================================

-- ============================================
-- EXTENSION: Enable pgvector
-- ============================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- TABLE: document_embeddings
-- Stores document chunks with vector embeddings
-- for semantic search and RAG operations
-- ============================================

CREATE TABLE document_embeddings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536) NOT NULL,
    header_path TEXT[] NOT NULL DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Composite unique constraint to prevent duplicate chunks
    CONSTRAINT unique_document_chunk UNIQUE (document_id, chunk_index)
);

-- ============================================
-- INDEXES: Vector Search Optimization
-- ============================================

-- HNSW index for fast approximate nearest neighbor search
-- m=16: Number of bi-directional links per node (read/write balance)
-- ef_construction=64: Size of dynamic candidate list during construction
CREATE INDEX idx_embeddings_hnsw ON document_embeddings 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- Fast lookup by document (for document deletion/updates)
CREATE INDEX idx_embeddings_document ON document_embeddings(document_id);

-- CRITICAL: Fast lookup by workspace for RLS pre-filtering
-- This index enables efficient workspace isolation before vector search
CREATE INDEX idx_embeddings_workspace ON document_embeddings(workspace_id);

-- GIN index on header_path for array containment queries
-- Enables efficient filtering by document structure (e.g., find all chunks under "Chapter 1")
CREATE INDEX idx_embeddings_header_path ON document_embeddings USING GIN(header_path);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE document_embeddings ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only access embeddings in their workspace
-- This ensures vector search results are automatically filtered by workspace membership
CREATE POLICY "workspace_isolation" ON document_embeddings
    FOR ALL
    USING (
        workspace_id IN (
            SELECT workspace_id FROM workspace_members 
            WHERE user_id = auth.uid()
        )
    );

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Function to delete all embeddings for a document
-- Used when a document is updated and needs re-embedding
CREATE OR REPLACE FUNCTION delete_document_embeddings(target_document_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM document_embeddings WHERE document_id = target_document_id;
END;
$$;

-- ============================================
-- COMMENTS: Documentation for future developers
-- ============================================

COMMENT ON TABLE document_embeddings IS 
'Stores document chunks with vector embeddings for semantic search. Each chunk represents a portion of a document with its embedding vector (1536 dimensions for OpenAI text-embedding-3-small).';

COMMENT ON COLUMN document_embeddings.embedding IS 
'Vector embedding (1536 dimensions) generated by OpenAI text-embedding-3-small model.';

COMMENT ON COLUMN document_embeddings.header_path IS 
'Array representing the hierarchical path of headers leading to this chunk (e.g., ["Introduction", "Background", "Problem Statement"]).';

COMMENT ON COLUMN document_embeddings.workspace_id IS 
'Denormalized workspace_id for efficient RLS pre-filtering. CRITICAL for security - ensures vector search respects workspace boundaries.';

COMMENT ON INDEX idx_embeddings_hnsw IS 
'HNSW index for approximate nearest neighbor search using cosine distance. Parameters: m=16 (connectivity), ef_construction=64 (build quality).';
